FROM alpine:3.20 AS builder

#编译ZeroTierOne
#https://git.alpinelinux.org/aports/tree/community/zerotier-one?id=eab757ac9e60bc25cf5d0c5b07785b12e7a4bb04

RUN apk upgrade --update \
	&& apk add linux-headers cargo openssl-dev \
	&& apk add make g++ \
	&& wget https://github.com/zerotier/ZeroTierOne/archive/refs/tags/.zip -O /zerotier.zip \
	&& unzip /zerotier.zip -d / \
	&& cd /ZeroTierOne- \
	&& make \
	&& make DESTDIR=/tmp/build install