name: Check last version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  sync-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "DTB"
          git config --global user.email "183888664+DoTheBetter@users.noreply.github.com"
        
      - name: Check Caddy version
        run: |
          set -e
          if [ ! -e "caddy_ver.txt" ];then
          	touch caddy_ver.txt
          fi

          version_old=$(cat caddy_ver.txt)
          version_new=$(curl -s https://api.github.com/repos/caddyserver/caddy/releases/latest | grep "tag_name" | cut -f4 -d "\"" | sed 's/^.//')
          echo "获取Release版本为 $version_new"
          echo "当前旧版本为 $version_old"

          if [ -z "$version_new" ]; then
            echo "错误：获取新版本为空。"
            version_new=$version_old
          fi

          if [ "$version_old" != "$version_new" ];then
            echo $version_new > caddy_ver.txt
            sed -ri "s/[0-9]+\.[0-9]+\.[0-9]+/$version_new/g" Dockerfile.caddy2
            git add .
            git commit -m "更新 Caddy Release 版本至 $version_new"
            git push

            #写入事件
            curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"event_type":"caddy2-on-update"}' https://api.github.com/repos/DoTheBetter/docker_baseimage/dispatches

          else
            echo "未检查到Caddy版本更新，已退出！"
          fi
          
      - name: Check ZeroTierOne version
        run: |
          set -e
          if [ ! -e "zerotier_ver.txt" ];then
          	touch zerotier_ver.txt
          fi

          version_old=$(cat zerotier_ver.txt)    
          version_new=$(curl -s https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest | grep "tag_name" | cut -f4 -d "\"")
          echo "获取Release版本为 $version_new"
          echo "当前旧版本为 $version_old"

          if [ -z "$version_new" ]; then
            echo "错误：获取新版本为空。"
            version_new=$version_old
          fi

          if [ "$version_old" != "$version_new" ];then
            echo $version_new > zerotier_ver.txt
            sed -ri "s/[0-9]+\.[0-9]+\.[0-9]+/$version_new/g" Dockerfile.zerotier
            git add .
            git commit -m "更新 ZeroTierOne Release 版本至 $version_new"
            git push

            #写入事件
            curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"event_type":"zerotier-on-update"}' https://api.github.com/repos/DoTheBetter/docker_baseimage/dispatches

          else
            echo "未检查到ZeroTierOne版本更新，已退出！"
          fi

      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2
