name: Docker baseimage：Caddy2

on:
  push:
    paths:
    - 'Dockerfile.caddy2'
  workflow_dispatch:  # 允许手动触发
  repository_dispatch:  # 允许事件类型为caddy2-on-update时被触发
    types:
      - caddy2-on-update

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "CADDY_VER=$(cat caddy_ver.txt)" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.caddy2
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/dothebetter/baseimage_caddy2:latest
            ghcr.io/dothebetter/baseimage_caddy2:${{ env.CADDY_VER }}
