name: Docker baseimage：Composerize

on:
  push:
    paths:
    - 'Dockerfile.composerize'
  workflow_dispatch:  # 允许手动触发
  repository_dispatch:  # 允许事件类型为composerize-on-update时被触发
    types:
      - composerize-on-update

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          versions=$(grep -oP '(?<==)\d+\.\d+\.\d+' composerize_ver.txt | paste -sd "-")
          echo "当前镜像版本号: $versions"
          echo "Composerize_VER=$versions" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.composerize
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/dothebetter/baseimage_composerize:latest
            ghcr.io/dothebetter/baseimage_composerize:${{ env.Composerize_VER }}
