name: Docker baseimage：ZeroTierOne

on:
  push:
    paths:
      - 'Dockerfile.zerotier'
  workflow_dispatch:  # 允许手动触发
  repository_dispatch:  # 允许事件类型为zerotier-on-update时被触发
    types:
      - zerotier-on-update

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "ZeroTierOne_VER=$(cat zerotier_ver.txt)" >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5-43
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.zerotier
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/dothebetter/baseimage_zerotier:latest
            ghcr.io/dothebetter/baseimage_zerotier:${{ env.ZeroTierOne_VER }}
